### ISSUE TITLE
【开源书籍】《深入架构原理与实践》

### ISSUE THREAD

**Issue by isno** [OpenGithubs/weekly#2]
- 项目名称：开源书籍《深入架构原理与实践》
- 项目地址：https://github.com/isno/theByteBook/
- 项目简介：深入讲解内核网络、Kubernetes、ServiceMesh、容器技术、分布式概论等现代化架构技术。也是经历实践检验的 DevOps、SRE 指南。
- 项目截图 ：
![屏幕截图](https://wx1.sinaimg.cn/mw2000/7cdda7f1gy1hjhuja6yibj223o2s0kjl.jpg)

**Comment by OpenGithubs** [comment]
收到自荐项目,后续会录入系统 增加推荐

**Comment by OpenGithubs** [comment]
已录入社区推荐系统:
推荐地址:https://open.itc.cn/github/dig?cateId=01H2M09172FGQRN8Q36VNXG3RK&repoId=R_kgDOIKTmzQ
![image](https://github.com/OpenGithubs/weekly/assets/116132402/ec122043-f990-44e2-bf81-855e9987c84a)
感谢您对社区的关注!
