### ISSUE TITLE
【开源自荐】wechatbc （类似开发公众号一样扩展个人微信号）

### ISSUE THREAD

**Issue by meteorOSS** [OpenGithubs/weekly#23]
项目介绍: 
采用插件化架构的框架设计，宿主程序仅提供基础功能，载入外部扩展jar插件以满足个人定制扩展功能

[https://github.com/meteorOSS/wechat-bc](https://github.com/meteorOSS/wechat-bc)

**Comment by OpenGithubs** [comment]
收到自荐项目
